language:
  cpp

dist: 
  trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libglew-dev
      - libglfw-dev
      - libopenal-dev

sudo:
  required

notifications:
  email: true

compiler:
  - gcc

env:
  global:
    - COMPILER=g++-7.1
  matrix:
    - CONFIG=Debug

before_install:
  - chmod +x build/premake5

script:
  - cd build && ./premake5 gmake
  - make -f Tests.make config=debug_linux64 && cd ..

after_script:
  - cd build && ./clear_build.sh && cd ..
