language:
  cpp

dist: 
  trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libglew-dev
      - libglfw-dev
      - libopenal-dev

sudo:
  required

notifications:
  email: true

compiler:
  - gcc

env:
  global:
    - COMPILER=g++-7.1
  matrix:
    - CONFIG=Debug
    - CONFIG=Release

script:
  - cd build && ./make_gmake.sh
  - make config=debug_linux64 all && cd ..

after_script:
  - cd build && ./clear_build.sh && cd ..
