language:
  cpp

dist: 
  trusty

addons:
  apt:
    sources:
    packages:
      - libglew1.13
      - libglfw-dev

sudo:
  required

notifications:
  email: true

compiler:
  - gcc

env:
  global:
  matrix:
    - CONFIG=Debug
    - CONFIG=Release

script:
  - cd build && makeGmake.sh
  - make all && cd ..

after_script:
  - cd build && clear_build.sh && cd ..