version: edencraft-{branch}-rev{build}

branches:
    only:
        - develop

max_jobs: 1

image: Visual Studio 2015

configuration:
    - Debug
    - Release

platform: x64

install:
    - cmd: cd build && makeVS15.bat && cd ..

build:
    project: build/EdenCraft.sln
    parallel: true
    verbosity: minimal

after_build:
    - cd build && clear_build.bat && cd ..
